#!/usr/bin/env bash
# Crawl 200 different search terms, each saving ~100 products to its own JSON file.
# Output: data/products/<term>.json
# Usage: bash scripts/run_all.sh

set -uo pipefail

# Activate virtualenv — path is relative to the project root
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="$(dirname "$SCRIPT_DIR")"
source "$PROJECT_DIR/.venv/bin/activate"

SEARCH_TERMS=(
  "iPhone 15 Pro"
  "Samsung Galaxy S24"
  "MacBook Pro M3"
  "Dell XPS laptop"
  "iPad Air"
  "Nintendo Switch OLED"
  "PlayStation 5 console"
  "Xbox Series X"
  "AirPods Pro"
  "Sony WH-1000XM5"
  "Apple Watch Series 9"
  "Samsung 4K TV"
  "OLED gaming monitor"
  "RTX 4090 graphics card"
  "AMD Ryzen 9 processor"
  "Canon EOS R6"
  "Sony A7 IV camera"
  "DJI drone"
  "GoPro Hero 12"
  "Kindle Paperwhite"
  "Nintendo Switch games"
  "PS5 games"
  "Xbox games"
  "Pokemon cards"
  "Magic the Gathering cards"
  "Funko Pop collectibles"
  "LEGO sets"
  "gaming chair"
  "mechanical keyboard"
  "gaming mouse"
  "USB-C hub"
  "external SSD"
  "wireless router"
  "smart home hub"
  "Raspberry Pi 5"
  "3D printer"
  "VR headset"
  "portable projector"
  "webcam 4K"
  "USB microphone"
  "Nike Air Jordan"
  "Adidas Yeezy"
  "Supreme hoodie"
  "vintage Levi jeans"
  "designer handbag"
  "Rolex watch"
  "Ray-Ban sunglasses"
  "Vans shoes"
  "New Era cap"
  "North Face jacket"
  "mountain bike"
  "road bike"
  "treadmill"
  "dumbbells set"
  "yoga mat"
  "tennis racket"
  "golf clubs set"
  "fishing rod"
  "camping tent"
  "hiking boots"
  "car stereo"
  "dash cam"
  "OBD2 scanner"
  "LED headlights"
  "car seat covers"
  "motorcycle helmet"
  "electric scooter"
  "car jump starter"
  "tire inflator"
  "car GPS navigator"
  "robot vacuum"
  "air purifier"
  "stand mixer"
  "Instant Pot"
  "coffee maker"
  "air fryer"
  "espresso machine"
  "blender"
  "food processor"
  "electric kettle"
  "vintage baseball cards"
  "comic books"
  "Star Wars collectibles"
  "Marvel action figures"
  "Hot Wheels cars"
  "vintage vinyl records"
  "coin collection"
  "stamps collection"
  "vintage postcards"
  "antique coins"
  "textbooks"
  "manga collection"
  "vinyl records"
  "DVD collection"
  "Blu-ray movies"
  "retro video game cartridges"
  "Nintendo 64 games"
  "PlayStation 1 games"
  "Atari games"
  "Game Boy games"
  "electric guitar"
  "acoustic guitar"
  "piano keyboard"
  "drum set"
  "bass guitar"
  "violin"
  "saxophone"
  "trumpet"
  "DJ controller"
  "audio interface"
  "baby stroller"
  "baby car seat"
  "baby monitor"
  "educational toys"
  "kids drone"
  "kids scooter"
  "dollhouse"
  "building blocks"
  "family board games"
  "1000 piece puzzle"
  "electric toothbrush"
  "Dyson hair dryer"
  "massage gun"
  "standing desk"
  "ergonomic office chair"
  "sleep tracker"
  "blood pressure monitor"
  "electric shaver"
  "curling iron"
  "face steamer"
  "premium dog food"
  "cat litter box"
  "pet camera"
  "dog harness"
  "cat tree"
  "fish tank aquarium"
  "reptile terrarium"
  "bird cage"
  "pet grooming kit"
  "dog crate"
  "wireless printer"
  "label maker"
  "standing desk converter"
  "monitor arm"
  "desk organizer"
  "wireless keyboard"
  "portable monitor"
  "power bank"
  "cable management"
  "laptop stand"
  "diamond ring"
  "gold necklace"
  "silver bracelet"
  "pearl earrings"
  "vintage brooch"
  "titanium ring"
  "gemstone pendant"
  "gold coin"
  "charm bracelet"
  "vintage watch"
  "cordless drill"
  "circular saw"
  "impact wrench"
  "multimeter"
  "soldering iron"
  "oscilloscope"
  "torque wrench"
  "socket set"
  "LED work light"
  "laser level"
  "cast iron skillet"
  "Dutch oven"
  "knife set"
  "cutting board"
  "spice rack"
  "sous vide cooker"
  "bread maker"
  "waffle maker"
  "electric grill"
  "food scale"
  "50mm camera lens"
  "camera tripod"
  "ND filters"
  "camera bag"
  "flash speedlight"
  "green screen"
  "ring light"
  "photo printer"
  "memory card"
  "camera battery"
  "luggage set"
  "travel pillow"
  "passport holder"
  "travel adapter"
  "packing cubes"
  "carry-on backpack"
  "money belt"
  "neck pillow travel"
  "portable charger travel"
  "travel toiletry bag"
  "mechanical watch"
  "smartwatch"
  "fitness tracker"
  "over-ear headphones"
  "in-ear monitor"
  "Bluetooth speaker"
  "soundbar"
  "subwoofer"
  "turntable vinyl"
  "amplifier"
)

cd "$PROJECT_DIR"
mkdir -p data/products

TOTAL=${#SEARCH_TERMS[@]}
echo "Starting crawl of $TOTAL search terms, ~100 products each."
echo "Output directory: data/products/"
echo ""

for i in "${!SEARCH_TERMS[@]}"; do
  term="${SEARCH_TERMS[$i]}"
  # Sanitize term for filename: lowercase, spaces to underscores, remove special chars
  filename=$(echo "$term" | tr '[:upper:]' '[:lower:]' | tr ' ' '_' | tr -cd '[:alnum:]_-')
  output="data/products/${filename}.json"

  echo "[$(( i + 1 ))/$TOTAL] Crawling: \"$term\" → $output"

  scrapy crawl ebay \
    -a search="$term" \
    -s CLOSESPIDER_ITEMCOUNT=100 \
    -O "$output" \
    2>&1 | grep -E "(item_scraped_count|ERROR|Spider closed)" | tail -3 || true

  echo ""
done

echo "Done. All results saved in data/products/"
